name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          # Options
          template: classic
          user: galaxyzxcv
          base: ""
          repositories_forks: no

          config_gemoji: yes
          config_animated: yes
          config_timezone: Asia/Shanghai

          # Plugins
          plugin_achievements: yes
          plugin_achievements_only: polyglot, stargazer, sponsor, deployer, member, maintainer, developer,scripter, packager, explorer, infographile, manager
          plugin_achievements_display: compact
          plugin_achievements_threshold: X
          
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          
          plugin_languages: yes
          plugin_languages_ignored: html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell, gnuplot # List of languages to ignore
          plugin_languages_sections: recently-used
          plugin_languages_details: lines, bytes-size # Additionally display total bytes size and percentage
          plugin_languages_indepth: yes # Get indepth stats (see documentation before enabling)
          plugin_languages_limit: 4
          
          plugin_skyline: yes
          plugin_skyline_frames: 120
